{
 "title": "SR Linux Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "NE", "query": { "query": "label_values(source)" } },
   {
    "name": "Logs",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Logging $NE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log: $Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{application=\"$Logs\", source=\"$NE\"}"
    }
   ]
  },
  {
   "title": "Total logs $NE",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 9, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (application) (count_over_time({source=\"$NE\"}[$__range]))",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Log volume: $Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({application=\"$Logs\",source=\"$NE\"} | logfmt [$__interval]))",
     "legendFormat": "{{level}}"
    }
   ]
  }
 ]
}