clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: syslog
  syslog:
    listen_address: 0.0.0.0:1514
    listen_protocol: udp
    idle_timeout: 300s
    label_structured_data: yes
    labels:
      job: "syslog"
  relabel_configs:
    - source_labels: ['__syslog_message_hostname']
      target_label: 'source'
    - source_labels: ['__syslog_message_severity']
      target_label: 'level'
    - source_labels: ['__syslog_message_app_name']
      target_label: 'application'
    - source_labels: ['__syslog_message_facility']
      target_label: 'facility'
    - source_labels: ['__syslog_message_proc_id']
      target_label: 'procid'
